# Change these first
owner: EOSC-synergy # Your GitHub organization or username
repo: o3as-status # Your GitHub repository name

# Add your sites here
sites:
  - name: O3as main website
    url: https://o3as.data.kit.edu
    __dangerous__disable_verify_peer: true
  - name: O3as WebApp (frontend)
    url: http://o3web.test.fedcloud.eu/
  - name: O3as WebApp (backend)
    url: http://o3web.test.fedcloud.eu:5000/plot
  - name: O3api (API production endpoint)
    url: https://api.o3as.fedcloud.eu/api/v1/ui/
    icon: https://upload.wikimedia.org/wikipedia/commons/a/ab/Swagger-logo.png
  - name: O3api - testing (API testing endpoint)
    url: http://o3api.test.fedcloud.eu:30505/api/v1/ui/
    icon: https://upload.wikimedia.org/wikipedia/commons/a/ab/Swagger-logo.png
  - name: O3api - development (API development endpoint)
    url: http://o3api.test.fedcloud.eu:30509/api/ui/
    icon: https://upload.wikimedia.org/wikipedia/commons/a/ab/Swagger-logo.png
  - name: O3as documentation
    url: https://o3as.readthedocs.io
    icon: https://github.com/readthedocs/readthedocs.org/blob/master/docs/img/logo.png
assignees: # Users to assign downtime issues (optional)
  - vykozlov
  - BorjaEst
status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  ## c.n.a.m.e.: status.o3as.fedcloud.eu
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /o3as-status
  #logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: o3as status monitoring
  introTitle: "Status monitoring of O3as services"
  introMessage: This is a **real-time** status page for [O3as](https://o3as.data.kit.edu) services.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
